name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn format:test
      - run: yarn build
      - uses: actions/configure-pages@v5
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      - uses: actions/upload-pages-artifact@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          path: .vitepress/dist
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v4
